name: wire
version: '2.17.2813'
summary: Secure and private chat with end-to-end encryption
description: |
  Text, voice, video and media on Wire are always end-to-end encrypted
  1:1 and in groups, so all your conversations are secure and private.
  Conversations are available on multiple devices and platforms without
  weakening security.

grade: stable
confinement: strict

parts:
  alsa-config:
    plugin: dump
    source: files/
    prepare: |
      sed -i 's/appname/wire/g' etc/alsa.conf
      sed -i 's/appname/wire/g' etc/alsa/cards/*.conf

  wire:
    plugin: dump
    source: https://wire-app.wire.com/linux/debian/pool/main/wire_$SNAPCRAFT_PROJECT_VERSION_amd64.deb
    prepare: |
      sed -i 's|Icon=wire-desktop|Icon=/usr/share/icons/hicolor/256x256/apps/wire-desktop\.png|g' usr/share/applications/wire-desktop.desktop
      execstack --clear-execstack opt/wire-desktop/wire-desktop
    after:
      - alsa-config
      - desktop-gtk2
    build-packages:
      - execstack
    stage-packages:
      - libasound2
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpulse0
      - libxss1
      - libxtst6

apps:
  wire:
    command: bin/desktop-launch $SNAP/opt/wire-desktop/wire-desktop
    desktop: usr/share/applications/wire-desktop.desktop
    # Correct the TMPDIR path for Chromium Framework/Electron to ensure
    # libappindicator has readable resources.
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - alsa
      - bluez
      - browser-support
      - camera
      - gsettings
      - home
      - mount-observe
      - network
      - opengl
      - pulseaudio
      - screen-inhibit-control
      - unity7
      - x11
