name: wire
version: '3.0.2816'
summary: Secure and private chat with end-to-end encryption
description: |
  Text, voice, video and media on Wire are always end-to-end encrypted
  1:1 and in groups, so all your conversations are secure and private.
  Conversations are available on multiple devices and platforms without
  weakening security.

grade: stable
confinement: strict

parts:
  alsa-config:
    plugin: dump
    source: alsa
    organize:
      alsa.conf: etc/alsa.conf

  alsa-lib:
    plugin: autotools
    source: http://archive.ubuntu.com/ubuntu/pool/main/a/alsa-lib/alsa-lib_1.1.3.orig.tar.bz2
    # source: ftp://ftp.alsa-project.org/pub/lib/alsa-lib-1.1.5.tar.bz2
    configflags:
    - --prefix=/usr
    - --sysconfdir=/etc
    - --libexec=/usr/lib
    - --libdir=/usr/lib
    - --localstatedir=/var
    - --with-configdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa
    - --with-plugindir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/alsa-lib
    - --disable-static
    organize:
      snap/wire/current/usr/lib/: usr/lib/
    stage:
    - usr/include
    - usr/lib
    prime:
    - -usr/bin
    - -usr/include
    - -usr/lib/pkgconfig
    - -usr/share/alsa/alsa.conf
    - -usr/share/alsa/pcm
    - -usr/share/alsa/topology/broadwell

  alsa-plugins:
    after: [alsa-lib]
    plugin: autotools
    source: http://archive.ubuntu.com/ubuntu/pool/main/a/alsa-plugins/alsa-plugins_1.1.1.orig.tar.bz2
    # source: ftp://ftp.alsa-project.org/pub/plugins/alsa-plugins-1.1.5.tar.bz2
    configflags:
    - --prefix=/usr
    - --sysconfdir=/etc
    - --libexec=/usr/lib
    - --libdir=/usr/lib
    - --localstatedir=/var
    - --disable-oss
    - --disable-usbstream
    - --disable-arcamav
    - --disable-avcodec
    - --with-plugindir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/alsa-lib
    - --disable-static
    organize:
      snap/wire/current/usr/lib/: usr/lib/
    stage:
    - usr/lib
    - usr/share/alsa
    build-packages:
    - libpulse-dev
    stage-packages:
    - libpulse0

  alsa:
    plugin: nil
    after: [alsa-plugins, alsa-lib, alsa-config]

  wire:
    after: [alsa]
    plugin: dump
    source: https://wire-app.wire.com/linux/debian/pool/main/wire_$SNAPCRAFT_PROJECT_VERSION_amd64.deb
    prepare: |
      sed -i 's|Icon=.*|Icon=/usr/share/icons/hicolor/256x256/apps/wire-desktop\.png|g' usr/share/applications/wire-desktop.desktop
      execstack --clear-execstack opt/wire-desktop/wire-desktop
    after:
    - alsa
    - desktop-gtk2
    build-packages:
    - execstack
    stage-packages:
    - libdb5.3
    - libgconf2-4
    - libgl1-mesa-glx
    - libglu1-mesa
    - libnotify4
    - libnspr4
    - libnss3
    - libpcre3
    - libpulse0
    - libxss1
    - libxtst6

apps:
  wire:
    command: bin/desktop-launch $SNAP/opt/wire-desktop/wire-desktop
    desktop: usr/share/applications/wire-desktop.desktop
    # Correct the TMPDIR path for Chromium Framework/Electron to ensure
    # libappindicator has readable resources.
    environment:
      ALSA_CONFIG_PATH: $SNAP/etc/alsa.conf
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
    - bluez
    - browser-support
    - camera
    - desktop
    - desktop-legacy
    - gsettings
    - home
    - mount-observe
    - network
    - network-bind
    - opengl
    - pulseaudio
    - screen-inhibit-control
    - unity7
    - wayland
    - x11
    # fudge me!
    - account-control
    - bluetooth-control
    - firewall-control
    - hardware-observe
    - netlink-audit
    - netlink-connector
    - network-control
    - network-observe
