name: wire
version: '3.0.2816'
summary: Secure and private chat with end-to-end encryption
description: |
  Text, voice, video and media on Wire are always end-to-end encrypted
  1:1 and in groups, so all your conversations are secure and private.
  Conversations are available on multiple devices and platforms without
  weakening security.

grade: stable
confinement: strict

parts:
  alsa-lib:
    plugin: autotools
    source: ftp://ftp.alsa-project.org/pub/lib/alsa-lib-1.1.5.tar.bz2
    configflags:
      - --prefix=/usr
      - --sysconfdir=/etc
      - --libexec=/usr/lib
      - --libdir=/usr/lib
      - --localstatedir=/var
      - --with-configdir=/snap/${SNAPCRAFT_PROJECT_NAME}/current/usr/share/alsa
      - --with-plugindir=/snap/${SNAPCRAFT_PROJECT_NAME}/current/usr/lib/alsa-lib
      - --disable-static
    prime:
      - -usr/bin
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/share/alsa/alsa.conf
      - -usr/share/alsa/pcm
      - -usr/share/alsa/topology/broadwell

  wire:
    plugin: dump
    source: https://wire-app.wire.com/linux/debian/pool/main/wire_$SNAPCRAFT_PROJECT_VERSION_amd64.deb
    prepare: |
      sed -i 's|Icon=wire-desktop|Icon=/usr/share/icons/hicolor/256x256/apps/wire-desktop\.png|g' usr/share/applications/wire-desktop.desktop
      execstack --clear-execstack opt/wire-desktop/wire-desktop
    after:
      - alsa-lib
      - desktop-gtk2
    build-packages:
      - execstack
    stage-packages:
      - libgconf2-4
      - libgl1-mesa-glx
      - libglu1-mesa
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6
    prime:
      - -usr/share/doc
      - -usr/share/man

apps:
  wire:
    command: bin/desktop-launch $SNAP/opt/wire-desktop/wire-desktop
    desktop: usr/share/applications/wire-desktop.desktop
    # Correct the TMPDIR path for Chromium Framework/Electron to ensure
    # libappindicator has readable resources.
    environment:
      ALSA_CONFIG_PATH: /snap/${SNAPCRAFT_PROJECT_NAME}/current/usr/share/alsa
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - alsa
      - bluez
      - browser-support
      - camera
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - mount-observe
      - network
      - opengl
      - pulseaudio
      - screen-inhibit-control
      - unity7
      - wayland
      - x11
